# Servidor
server:
  servlet:
    context-path: /fondosvoluntarios/

# Spring Config
spring:
  # Conexion DB PostgreSQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

# Flyway configuration
flyway:
  mixed: true
  clean-disabled: true

# Cors
cors:
  url-permitida: https://local.suranet.com:4200
